[package]
name = "ckb-testtool"
version = "0.2.1"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"
license = "MIT"
description = "CKB contract testing tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-always-success-script = "0.0.1"
ckb-tool = "0.2.1"
rand = "0.7"
lazy_static = "1.4"
linked_hash_set = "0.1"

[dev-dependencies]
ckb-system-scripts = "0.5"
